title: Planetary Computer Tasks Function packages and Helm charts
description: This site stores Function package zip files and Helm chart tarballs for the Planteary Computer Tasks project
theme: minima
url: "https://microsoft.github.io/planetary-computer-tasks"
repo_name: planetary-computer-tasks

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  