{{- if .Values.pctasks.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pctasks.serviceAccountName" . }}
  labels:
    {{- include "pctasks.labels" . | nindent 4 }}
  {{- with .Values.pctasks.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
