apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: pc-tasks-ingress
  name: nginx-configuration
  namespace: {{ .Values.namespace }}
data:
  use-forwarded-headers: "true"
  enable-real-ip: "true"