kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pctasks
  namespace: pc
subjects:
  - kind: ServiceAccount
    name: pctasks-sa
    namespace: pc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pctasks
