environment: "staging"

pctasks:
  image:
    # e.g. myacr.azurecr.io/my-repository
    repository: ""
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 80
    annotations: {}

  server:
    webConcurrency: "1"

  deploy:
    replicaCount: 1
    podAnnotations: {}
    imagePullSecrets: []
    securityContext: {}
    podSecurityContext: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    autoscaling:
      enabled: false

  cert:
    privateKeySecretRef: "letsencrypt-staging"
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    issuerEmail: ""
    secretName: ""

  host: "0.0.0.0"
  port: "80"
  appRootPath: ""
  debug: "FALSE"

  ingress:
    enabled: false
    annotations: {}

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  nameOverride: ""
  fullnameOverride: ""