services:
  deploy:
    container_name: pc-etl-deploy
    image: pc-etl-deploy
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      # For Terraform
      - TF_VAR_username=${USER}
      - ARM_SUBSCRIPTION_ID=${subscriptionId}
      - ARM_TENANT_ID=${tenantId}
      - ARM_CLIENT_ID=${servicePrincipalId}
      - ARM_CLIENT_SECRET=${servicePrincipalKey}

      # For Azure CLI
      - AZURE_TENANT_ID=${tenantId}
      - AZURE_CLIENT_ID=${servicePrincipalId}
      - AZURE_CLIENT_SECRET=${servicePrincipalKey}

    working_dir: /opt/src/deployment
    volumes:
      - ../deployment:/opt/src/deployment
      - ../pctasks:/opt/src/pctasks:ro
      - ../pctasks_funcs:/opt/src/pctasks_funcs:ro
